package com.auction.network;

import java.io.Serializable;

public enum MessageType implements Serializable {
    REGISTER_ADMIN,
    REGISTER_BIDDER,
    ITEM_REQUEST,
    ITEM_PENDING,
    APPROVE_ITEM,
    REJECT_ITEM,
    DELETE_ITEM,
    ITEM_APPROVED,
    ITEM_REJECTED,
    DEPOSIT_REQUEST,
    DEPOSIT_PENDING,
    APPROVE_DEPOSIT,
    REJECT_DEPOSIT,
    DEPOSIT_APPROVED,
    DEPOSIT_REJECTED,
    BID,
    BID_HISTORY,
    SYNC_BID_HISTORY,
    AUCTION_OPENED,
    AUCTION_STOPPED,
    SYNC_AUCTIONS,
    AUCTION_ENDED,
    ERROR
}
